In [2]:
import pandas as pd
import seaborn as sns

In [3]:
data=pd.read_csv('datasets/adult.data.csv',index_col=False)
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

1. How many men and women (sex feature) are represented in this dataset?

In [18]:
# data.groupby('sex').size()
data['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

2. What is the average age (age feature) of women?

In [17]:
data['age'][data['sex']=='Female'].mean()

np.float64(36.85823043357163)

3. What is the percentage of German citizens (native-country feature)?

In [34]:
float((data["native-country"] == "Germany").sum()) / data.shape[0]

0.004207487485028101

4-5. What are mean value and standard deviation of the age of those who receive more than 50K per year (salary feature) and those who receive less than 50K per year?

In [42]:
data.groupby(data['salary']=='>50K')['age'].agg(['mean','std'])

             mean        std
salary
False   36.783738  14.020088
True    44.249841  10.519028

6. Is it true that people who earn more than 50K have at least high school education? (education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters or Doctorate feature)

In [49]:
data[data['salary']==">50K"]['education'].value_counts()
#NO

education
Bachelors       2221
HS-grad         1675
Some-college    1387
Masters          959
Prof-school      423
Assoc-voc        361
Doctorate        306
Assoc-acdm       265
10th              62
11th              60
7th-8th           40
12th              33
9th               27
5th-6th           16
1st-4th            6
Name: count, dtype: int64

7. Display age statistics for each race (race feature) and each gender (sex feature). Use groupby() and describe(). Find the maximum age of men of Amer-Indian-Eskimo race.

In [52]:
data.groupby(by=['race','sex'])['age'].describe()

                             count       mean        std   min   25%   50%  \
race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                             75%   max
race               sex
Amer-Indian-Eskimo Female  46.00  80.0
                   Male    45.00  82.0
Asian-Pac-Islander Female  43.75  75.0
                   Male    46.00  90.0
Black              Female  46.00  90.0
                   Male    46.00  90.0
Other              Female  39.00  74.0
                   Male    42.00  77.0
White              Female  46.00  90.0
                   Male    49.00  90.0

8. Among whom is the proportion of those who earn a lot (>50K) greater: married or single men (marital-status feature)? Consider as married those who have a marital-status starting with Married (Married-civ-spouse, Married-spouse-absent or Married-AF-spouse), the rest are considered bachelors.

In [63]:
data.groupby(data['marital-status'][data['sex']=='Male'].str.startswith("Married"))['salary'].value_counts(normalize=True)

marital-status  salary
False           <=50K     0.915505
                >50K      0.084495
True            <=50K     0.559486
                >50K      0.440514
Name: proportion, dtype: float64

9. What is the maximum number of hours a person works per week (hours-per-week feature)? How many people work such a number of hours and what is the percentage of those who earn a lot among them?

In [80]:
max_hours = data['hours-per-week'].max()

data[data['hours-per-week'] == max_hours]['salary'].value_counts(normalize=True)

salary
<=50K    0.705882
>50K     0.294118
Name: proportion, dtype: float64

10. Count the average time of work (hours-per-week) those who earn a little and a lot (salary) for each country (native-country).

In [ ]:
pd.crosstab(
    data["native-country"],
    data["salary"],
    values=data["hours-per-week"],
    aggfunc=np.mean,
).T

TypeError: agg function failed [how->mean,dtype->object]